# fly.toml app configuration file generated for xcode-cloud-webhook-for-discord on 2024-04-30T23:57:43+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'xcode-cloud-webhook-for-discord'
primary_region = 'sjc'

[build]

[http_service]
  internal_port = 3000
  force_https = false
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
  memory = '1gb'
